name: tandu_run
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  get: ^4.6.5
  flutter_svg: ^1.0.3
  intl: ^0.18.1
  date_picker_timeline: ^1.2.5
  animated_text_kit: ^4.2.2
  sliding_up_panel: ^2.0.0+1
  horizontal_week_calendar: ^0.0.11
  http: ^0.13.5
  shared_preferences: ^2.0.20
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - semuaAsset/
    - semuaAsset/gambar/awal.png
    - semuaAsset/gambar/home.png
    - semuaAsset/gambar/kelola.png
    - semuaAsset/gambar/informasi.png
    - semuaAsset/gambar/home_molekul.png
    - semuaAsset/gambar/home_ph.png
    - semuaAsset/gambar/home_volume.png
    
    

  fonts:
    - family: Inter
      fonts:
        - asset: semuaAsset/font/inter_regular.ttf
          weight: 400
        - asset: semuaAsset/font/inter_medium.ttf
          weight: 500
        - asset: semuaAsset/font/inter_semibold.ttf
          weight: 600
        - asset: semuaAsset/font/inter_bold.ttf
          weight: 700
        - asset: semuaAsset/font/inter_extrabold.ttf
          weight: 800
        - asset: semuaAsset/font/inter_black.ttf
          weight: 900
        - asset: semuaAsset/font/Inter_Thin.ttf
          weight: 400
        - asset: semuaAsset/font/Inter_Light.ttf
          weight: 300
